name: Build and Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4.2.2

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: '21'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm cache clean --force
          npm install

      # Step 4: Run the script
      - name: Run script.js
        run: node script.js

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: output
          clean: true
          single-commit: true
